// Data of car makes and models

export const carData = {
    "AC": ["Model 1", "Model 2"],
    "Acura": ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "4C"],
    "Audi": ["A3", "A4", "A5", "A6", "A7", "Q3", "Q5", "Q7", "Q8"],
    "Bentley": ["Bentayga", "Continental", "Flying Spur"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "X1", "X3", "X5", "X7", "Z4"],
    "Buick": ["Enclave", "Encore", "Envision", "Lacrosse", "Regal"],
    "Cadillac": ["ATS", "CT4", "CT5", "CT6", "Escalade", "XT4", "XT5", "XT6"],
    "Chevrolet": ["Blazer", "Camaro", "Colorado", "Corvette", "Equinox", "Malibu", "Silverado", "Suburban", "Tahoe", "Traverse"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Dodge": ["Challenger", "Charger", "Durango", "Journey"],
    "Ferrari": ["488", "812", "F8", "Portofino", "Roma"],
    "Fiat": ["124 Spider", "500", "500X"],
    "Ford": ["Bronco", "Edge", "Escape", "Expedition", "Explorer", "F-150", "Fusion", "Mustang", "Ranger"],
    "Genesis": ["G70", "G80", "G90"],
    "GMC": ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
    "Honda": ["Accord", "Civic", "CR-V", "Fit", "HR-V", "Insight", "Odyssey", "Passport", "Pilot", "Ridgeline"],
    "Hyundai": ["Elantra", "Kona", "Palisade", "Santa Fe", "Sonata", "Tucson", "Veloster"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80"],
    "Jaguar": ["E-Pace", "F-Pace", "F-Type", "XE", "XF"],
    "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
    "Kia": ["Forte", "K5", "Niro", "Optima", "Seltos", "Sorento", "Soul", "Sportage", "Stinger", "Telluride"],
    "Lamborghini": ["Aventador", "Huracan", "Urus"],
    "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Lexus": ["ES", "GS", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "UX"],
    "Lincoln": ["Aviator", "Corsair", "MKC", "MKT", "MKX", "Navigator"],
    "Maserati": ["Ghibli", "Levante", "Quattroporte"],
    "Mazda": ["CX-3", "CX-30", "CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
    "McLaren": ["570S", "600LT", "720S", "GT"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "G-Class", "GLA", "GLC", "GLE", "GLS", "S-Class", "SL", "SLC"],
    "MINI": ["Clubman", "Convertible", "Countryman", "Hardtop 2 Door", "Hardtop 4 Door"],
    "Mitsubishi": ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
    "Nissan": ["Altima", "Armada", "Frontier", "Kicks", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Titan", "Versa"],
    "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
    "Ram": ["1500", "2500", "3500", "ProMaster"],
    "Subaru": ["Ascent", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "WRX"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y"],
    "Toyota": ["4Runner", "Avalon", "Camry", "Corolla", "Highlander", "Land Cruiser", "Prius", "RAV4", "Sequoia", "Sienna", "Tacoma", "Tundra"],
    "Volkswagen": ["Atlas", "Golf", "Jetta", "Passat", "Tiguan"],
    "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"]
};
